version: '3.8'

services:
  manual_plataforma:
    image: autonomia/manual:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.manual_plataforma.rule=Host(`plataforma.autonomia.site`)"
        - "traefik.http.routers.manual_plataforma.entrypoints=websecure"
        - "traefik.http.routers.manual_plataforma.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.manual_plataforma.priority=1"
        - "traefik.http.routers.manual_plataforma.service=manual_plataforma"
        - "traefik.http.services.manual_plataforma.loadbalancer.server.port=80"
        - "traefik.http.services.manual_plataforma.loadbalancer.passhostheader=true"
        - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.routers.manual_plataforma.middlewares=sslheader@docker"
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  network_public:
    external: true
