version: '3.8'

services:
  manual-autonomia:
    image: autonomia/manual:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.manual_autonomia.rule=Host(`plataforma.autonomia.site`)"
        - "traefik.http.routers.manual_autonomia.entrypoints=websecure"
        - "traefik.http.routers.manual_autonomia.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.manual_autonomia.priority=1"
        - "traefik.http.routers.manual_autonomia.service=manual_autonomia"
        - "traefik.http.services.manual_autonomia.loadbalancer.server.port=80"
        - "traefik.http.services.manual_autonomia.loadbalancer.passhostheader=true"
        - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.routers.manual_autonomia.middlewares=sslheader@docker"
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  network_public:
    external: true
