version: '3.8'

services:
  manual-autonomia:
    image: autonomia/manual:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.manual-autonomia.rule=Host(`manual.autonomia.io`)"  # Substitua pelo seu domínio
        - "traefik.http.routers.manual-autonomia.entrypoints=websecure"
        - "traefik.http.routers.manual-autonomia.tls.certresolver=myresolver"
        - "traefik.http.services.manual-autonomia.loadbalancer.server.port=80"
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true
